spring:
  application:
    name: tutorial-web
  datasource:
    url: jdbc:mysql://47.92.29.113:3307/tutorial_web?characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 


  redis:
    port: 6379
    host: 47.92.29.113
    password: 
    jedis:
      pool:
        # 连接池最大连接数，若为负数则表示没有任何限制
        max-active: 8
        # 连接池最大阻塞等待时间，若为负数则表示没有任何限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    database: 2
server:
  port: 450

markerhub:
  jwt:
    secret: 
    expire: 604800
    header: Authorization




