spring:
  profiles:
    active: dev
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # controller 去掉为null的字段
  jackson:
    default-property-inclusion: non_null

serverAddress : http://47.92.29.113

# 日志配置
logging:
  level:
    net.tutorial: debug
    org.springframework: warn

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql


mybatis-plus:
  type-aliases-package: net.tutorial.domain
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configLocation: classpath:mybatis/mybatis-config.xml
  global-config:
    db-config:
      id-type: auto
#      logic-delete-field: deleted


# 项目相关配置
tutorial:
  # 名称
  name: tutorial
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2024
  # 文件路径 示例（ Windows配置D:/tutorial/uploadPath，Linux配置 /home/tutorial/uploadPath）
#  profile: G:/tutorial/uploadPath
  profile: /home/tutorial/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math
  #默认头像
  defaultAvatar: /profile/upload/2024/02/21/default_avatar_20240221160354A001.png

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）30
  expireTime: 720

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10






